# Generated by Django 5.2.12 on 2026-04-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='nombre',
        ),
        migrations.AddField(
            model_name='registro',
            name='chip',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='registro',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='registro',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='registro',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='lote',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registro',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registro',
            name='raza',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='registro',
            name='sector',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registro',
            name='sexo',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
