# Generated by Django 5.2.12 on 2026-04-12 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_remove_registro_descripcion_remove_registro_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='numero',
        ),
    ]
